
#include <iostream>
#include <vector>
#include <string>
#include <iomanip>
#include <algorithm>
#include <limits>

using namespace std;

// Structure to store course-specific data
struct Course {
    string name;
    string letterGrade;
    double points;
    int credits;
    string status; // PASS or FAIL
};

// Function to convert Letter Grade to 4.0 Scale Grade Points
double calculatePoints(string letter) {
    transform(letter.begin(), letter.end(), letter.begin(), ::toupper);
    if (letter == "A+" || letter == "A") return 4.0;
    if (letter == "A-") return 3.7;
    if (letter == "B+") return 3.3;
    if (letter == "B") return 3.0;
    if (letter == "B-") return 2.7;
    if (letter == "C+") return 2.3;
    if (letter == "C") return 2.0;
    if (letter == "C-") return 1.7;
    if (letter == "D") return 1.0;
    if (letter == "F") return 0.0;
    return -1.0; 
}

int main() {
    string studentName, rollNo, collegeName;
    int numCourses;
    vector<Course> semester;

    cout << "========================================" << endl;
    cout << "    UNIVERSITY GRADE MANAGEMENT SYSTEM" << endl;
    cout << "========================================" << endl;

    // Academic Identity Inputs
    cout << "Enter College/University Name: "; 
    getline(cin, collegeName);
    cout << "Enter Student Full Name      : "; 
    getline(cin, studentName);
    cout << "Enter University Roll No     : "; 
    getline(cin, rollNo);

    // Number of courses with validation
    cout << "Enter Number of Courses      : ";
    while (!(cin >> numCourses) || numCourses <= 0) {
        cout << "[!] Please enter a valid number (1 or more): ";
        cin.clear();
        cin.ignore(numeric_limits<streamsize>::max(), '\n');
    }

    // Data Collection Loop
    for (int i = 0; i < numCourses; i++) {
        Course c;
        cout << "\n--- Entry for Course " << i + 1 << " ---" << endl;
        cout << "Course Name: "; 
        cin.ignore(); 
        getline(cin, c.name);
        
        while (true) {
            cout << "Letter Grade (A, B, C, D, F): "; 
            cin >> c.letterGrade;
            c.points = calculatePoints(c.letterGrade);
            if (c.points != -1.0) break;
            cout << "[!] Invalid Grade. Please try again." << endl;
        }
        
        cout << "Credit Hours: ";
        while (!(cin >> c.credits) || c.credits < 0) {
            cout << "[!] Invalid Credits. Enter a positive number: "; 
            cin.clear(); 
            cin.ignore(numeric_limits<streamsize>::max(), '\n');
        }

        c.status = (c.points > 0.0) ? "PASS" : "FAIL";
        semester.push_back(c);
    }

    // Calculations
    double totalWeightedPoints = 0;
    int totalCredits = 0;
    bool hasFailedAny = false;

    for (const auto& c : semester) {
        totalWeightedPoints += (c.points * c.credits);
        totalCredits += c.credits;
        if (c.status == "FAIL") hasFailedAny = true;
    }

    double gpa = (totalCredits > 0) ? (totalWeightedPoints / totalCredits) : 0;
    double percentage = gpa * 9.5; // Standard GPA to Percentage conversion

    // Final Official Report Display
    cout << "\n" << string(70, '=') << endl;
    
    // Centering the College Name for the header
    transform(collegeName.begin(), collegeName.end(), collegeName.begin(), ::toupper);
    cout << setw(35 + collegeName.length()/2) << collegeName << endl;
    
    cout << "                    OFFICIAL ACADEMIC TRANSCRIPT" << endl;
    cout << string(70, '=') << endl;
    cout << " NAME    : " << left << setw(25) << studentName << " | ROLL NO: " << rollNo << endl;
    cout << string(70, '-') << endl;
    cout << left << setw(25) << "SUBJECT" << setw(10) << "GRADE" << setw(10) << "POINTS" << setw(10) << "CREDITS" << "STATUS" << endl;
    cout << string(70, '-') << endl;

    for (const auto& c : semester) {
        string shortName = (c.name.length() > 22 ? c.name.substr(0, 19) + "..." : c.name);
        cout << left << setw(25) << shortName 
             << setw(10) << c.letterGrade 
             << setw(10) << fixed << setprecision(2) << c.points 
             << setw(10) << c.credits 
             << c.status << endl;
    }

    cout << string(70, '-') << endl;
    cout << " FINAL GPA    : " << fixed << setprecision(2) << gpa << " / 4.00" << endl;
    cout << " PERCENTAGE   : " << fixed << setprecision(1) << percentage << "%" << endl;
    cout << " TOTAL CREDITS: " << totalCredits << endl;
    
    cout << " ACADEMIC STANDING: ";
    if (hasFailedAny) cout << "CONTAINS FAILURES ⚠️";
    else if (gpa >= 3.8) cout << "SUMMA CUM LAUDE 🎓";
    else if (gpa >= 3.5) cout << "DEAN'S LIST ⭐";
    else cout << "GOOD STANDING ✅";
    
    cout << "\n" << string(70, '=') << endl;
    cout << "        Generated by: Academic Grade Management System" << endl;
    cout << string(70, '=') << endl;

    return 0;
}
